=== linkareti/rec-project/last-successfull/eLab/rec/src/java/ui/com/linkare/rec/impl/baseUI/config/ReCBaseUIConfig.dtd
<?xml version='1.0' encoding='UTF-8'?>
 

<!ELEMENT DefaultAcquisitionConfig EMPTY>
<!ATTLIST DefaultAcquisitionConfig
    order CDATA #REQUIRED
    displayStringBundleKey CDATA #REQUIRED
    iconLocationBundleKey CDATA ""
    toolTipBundleKey CDATA ""
    classLocationBundleKey CDATA #REQUIRED
  >
  
  
<!ELEMENT Display EMPTY>
<!ATTLIST Display
    order CDATA #REQUIRED
    offlineCapable (true|false|0|1|yes|no) "false"
    displayStringBundleKey CDATA #REQUIRED
    iconLocationBundleKey CDATA ""
    toolTipBundleKey CDATA ""
    classLocationBundleKey CDATA #REQUIRED
  >

<!ELEMENT Apparatus (DefaultAcquisitionConfig|Display|WebResource|LocalizationBundle)*>
<!ATTLIST Apparatus
    order CDATA #REQUIRED
    displayStringBundleKey CDATA #REQUIRED
    displayFactoryClassLocationBundleKey CDATA ""
    iconLocationBundleKey CDATA ""
    toolTipBundleKey CDATA ""
    dataModelClassLocationBundleKey CDATA ""
    videoLocation CDATA ""
    headerDisplayClassLocationBundleKey CDATA ""
    location CDATA #REQUIRED
    customizerClassLocationBundleKey CDATA #REQUIRED
  >

<!ELEMENT Lab (Apparatus|WebResource|LocalizationBundle)*>
<!ATTLIST Lab
    order CDATA #REQUIRED
    iconLocationBundleKey CDATA ""
    toolTipBundleKey CDATA ""
    displayStringBundleKey CDATA #REQUIRED
    location CDATA #REQUIRED
  >

<!ELEMENT WebResource EMPTY>
<!ATTLIST WebResource
    order CDATA #REQUIRED
    internalBrowser (true|false|0|1|yes|no) "false"
    toolTipLocationBundleKey CDATA ""
    displayStringBundleKey CDATA #REQUIRED
    iconLocationBundleKey CDATA ""
    locationBundleKey CDATA #REQUIRED
  >

<!ELEMENT LocalizationBundle EMPTY>
<!ATTLIST LocalizationBundle
    location CDATA #REQUIRED
    name CDATA #REQUIRED
  >

<!ELEMENT ReCBaseUIConfig (Lab|WebResource|LocalizationBundle)*>
<!ATTLIST ReCBaseUIConfig
    aboutPageLocationBundleKey CDATA ""
    autoConnectLab (true|false|0|1|yes|no) "false"
    showVideoFrame (true|false|0|1|yes|no) "false"
    enableVideoFrame (true|false|0|1|yes|no) "true"
    showChatFrame (true|false|0|1|yes|no) "false"
    enableChatFrame (true|false|0|1|yes|no) "true"
    showUserList (true|false|0|1|yes|no) "false"
    enableUsersList (true|false|0|1|yes|no) "true"
    usersListRefreshRateMs CDATA "2000"
    enterApparatusChatRoom (true|false|0|1|yes|no) "false"
    iconLocationBundleKey CDATA ""
    frameTitleBundleKey CDATA #REQUIRED
    iconSponsorLocationBundleKey CDATA ""
    helpPageLocationBundleKey CDATA ""
  >

=== linkareti/rec-project/templates/client/ReCBaseUIConfig.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Created by bruno on 21 de Maio de 2003, 17:33 -->
<!-- Altered by jp on 22 de Janeiro de 2004, 01:40 -->
<!--<!DOCTYPE ReCBaseUIConfig SYSTEM "ReCBaseUIConfig.dtd">-->
<!-- The strings specified here should be entries on a localized Resource Bundle -->
<ReCBaseUIConfig autoConnectLab="false" showVideoFrame="false" enableVideoFrame="false" showChatFrame="true" enableChatFrame="true" showUserList="true" enableUsersList="true" enableLoginPassword="false" usersListRefreshRateMs="10000" enterApparatusChatRoom="true" iconLocationBundleKey="ReCBaseUI$rec.bui.icon.frame" frameTitleBundleKey="ReCBaseUI$rec.bui.title.frame" iconSponsorLocationBundleKey="bundleName#bundleKey" helpPageLocationBundleKey="ReCBaseUI$rec.bui.url.help" aboutPageLocationBundleKey="ReCBaseUI$rec.bui.url.about" splashIconLocationBundleKey="ReCBaseUI$rec.bui.icon.splash">
    <LocalizationBundle name="ReCBaseUI" location="recresource:///com/linkare/rec/impl/baseUI/resources/ReCBaseUI"/>
    <LocalizationBundle name="ReCLabeLab" location="recresource:///pt/utl/ist/elab/resources/ReCLabeLab"/>
    <LocalizationBundle name="ReCLabeLabVirtual" location="recresource:///pt/utl/ist/elab/resources/ReCLabeLabVirtual"/>

    <LocalizationBundle name="g" location="recresource:///pt/utl/ist/elab/client/g/resources/messages"/>

    
    <LocalizationBundle name="ReCExpSemiconductors" location="recresource:///pt/utl/ist/elab/virtual/client/semiconductor/resources/ReCExpSemiconductors"/>
    <LocalizationBundle name="ReCExpScuba" location="recresource:///pt/utl/ist/elab/client/serial/stamp/scuba/resources/ReCExpScuba"/>
    <LocalizationBundle name="ReCExpRadio" location="recresource:///pt/utl/ist/elab/client/serial/stamp/radioactividade/resources/ReCExpRadio"/>
    <LocalizationBundle name="ReCExpPendulo" location="recresource:///pt/utl/ist/elab/client/serial/stamp/pendulo/resources/ReCExpPendulo"/>
    <LocalizationBundle name="ReCExpPV" location="recresource:///pt/utl/ist/elab/client/serial/stamp/pv/resources/ReCExpPV"/>
    <LocalizationBundle name="ReCExpPlanck" location="recresource:///pt/utl/ist/elab/client/serial/stamp/planck/resources/ReCExpPlanck"/>
    <LocalizationBundle name="ReCExpDiscos" location="recresource:///pt/utl/ist/elab/client/serial/stamp/momentoInercia/resources/ReCExpDiscos"/>
    <LocalizationBundle name="ReCExpAleatorio" location="recresource:///pt/utl/ist/elab/client/Aleatorio/Resource/ReCExpAleatorio"/>
    <LocalizationBundle name="ReCExpT" location="recresource:///pt/utl/ist/elab/client/serial/stamp/conducaoCalor/resources/ReCExpT"/>
    <LocalizationBundle name="ReCExpMeteo" location="recresource:///pt/utl/ist/elab/client/meteo/resources/ReCExpMeteo"/>
    <LocalizationBundle name="ReCExpStatSound" location="recresource:///pt/utl/ist/elab/client/serial/stamp/statsound/resources/ReCExpStatSound"/>
    <LocalizationBundle name="ReCExpWebRobot" location="recresource:///pt/utl/ist/elab/client/webrobot/resources/ReCExpWebRobot"/>
    <LocalizationBundle name="ReCExpThomson" location="recresource:///pt/utl/ist/elab/client/serial/stamp/thomson/resources/ReCExpThomson"/>
    <LocalizationBundle name="ReCExpPolaroid" location="recresource:///pt/utl/ist/elab/client/usb/cypress/polaroid/resources/ReCExpPolaroid"/>
    <LocalizationBundle name="ReCExpGamma" location="recresource:///pt/utl/ist/elab/client/usb/cypress/gamma/resources/ReCExpGamma"/>
    <LocalizationBundle name="ReCExpTelescopio" location="recresource:///pt/utl/ist/elab/client/telescopio/resources/ReCExpTelescopio"/>
    <LocalizationBundle name="ReCExpPG" location="recresource:///pt/utl/ist/elab/client/serial/stamp/penduloGravitico/resources/ReCExpPG"/>
    <LocalizationBundle name="ReCExpCC" location="recresource:///pt/utl/ist/elab/client/serial/stamp/condensadorCilindrico/resources/ReCExpCC"/>
	<LocalizationBundle name="ReCExpMM" location="recresource:///pt/utl/ist/elab/virtual/client/mm/resources/ReCExpMM"/>
    <LocalizationBundle name="ReCExpCG" location="recresource:///pt/utl/ist/elab/virtual/client/cg/resources/ReCExpCG"/>
    <LocalizationBundle name="ReCExpM3" location="recresource:///pt/utl/ist/elab/virtual/client/m3/resources/ReCExpM3"/>
    <LocalizationBundle name="ReCExpSTDMAP" location="recresource:///pt/utl/ist/elab/virtual/client/stdmap/resources/ReCExpSTDMAP"/>
    <LocalizationBundle name="ReCExpPend2M" location="recresource:///pt/utl/ist/elab/virtual/client/pend2m/resources/ReCExpPend2M"/>
    <LocalizationBundle name="ReCExpFERMAP" location="recresource:///pt/utl/ist/elab/virtual/client/fermap/resources/ReCExpFERMAP"/>
    <LocalizationBundle name="ReCExpMovProj" location="recresource:///pt/utl/ist/elab/virtual/client/movproj/resources/ReCExpMovProj"/>
    <LocalizationBundle name="ReCExpCargas3D" location="recresource:///pt/utl/ist/elab/virtual/client/cargas3d/resources/ReCExpCargas3D"/>
    <LocalizationBundle name="ReCExpMvBrown" location="recresource:///pt/utl/ist/elab/virtual/client/mvbrown/resources/ReCExpMvBrown"/>
    <LocalizationBundle name="ReCExpQuantum" location="recresource:///pt/utl/ist/elab/virtual/client/quantum/resources/ReCExpQuantum"/>
    <LocalizationBundle name="ReCExpCartPole" location="recresource:///pt/utl/ist/elab/virtual/client/cartpole/resources/ReCExpCartPole"/>
    <LocalizationBundle name="ReCExpYoungInterf" location="recresource:///pt/utl/ist/elab/virtual/client/younginterf/resources/ReCExpYoungInterf"/>
    <LocalizationBundle name="ReCExpBS" location="recresource:///pt/utl/ist/elab/virtual/client/bs/resources/ReCExpBS"/>
    <LocalizationBundle name="ReCExpLooping" location="recresource:///pt/utl/ist/elab/virtual/client/looping/resources/ReCExpLooping"/>
    <LocalizationBundle name="ReCExpTiro" location="recresource:///pt/utl/ist/elab/virtual/client/tiro/resources/ReCExpTiro"/>
    <LocalizationBundle name="ReCExpDI" location="recresource:///pt/utl/ist/elab/virtual/client/di/resources/ReCExpDI"/>
    <LocalizationBundle name="ReCExpColisao" location="recresource:///pt/utl/ist/elab/virtual/client/colisao/resources/ReCExpColisao"/>
    <LocalizationBundle name="ReCExpOscilador" location="recresource:///pt/utl/ist/elab/virtual/client/oscilador/resources/ReCExpOscilador"/>
    <LocalizationBundle name="ReCExpPoisson" location="recresource:///pt/utl/ist/elab/virtual/client/poisson/resources/ReCExpPoisson"/>
    
    <WebResource locationBundleKey="ReCLabeLab$rec.lab.url.eescola" iconLocationBundleKey="ReCLabeLab$rec.lab.icon.webpage" displayStringBundleKey="ReCLabeLab$rec.lab.url.title.eescola" toolTipLocationBundleKey="ReCLabeLab$rec.lab.url.tip.eescola" internalBrowser="false" order="1"/>
    <!--<WebResource locationBundleKey="ReC_Base_Test$web_url_linkare" 
		 iconLocationBundleKey="ReC_Base_Test$web_icon" 
		 displayStringBundleKey="ReC_Base_Test$web_title_linkare"  
5A
		 toolTipLocationBundleKey="ReC_Base_Test$web_tip_linkare"   
		 internalBrowser="false"
		 order="2"/>-->
    
    <Lab location="corbaloc:iiop:1.2@elab.ist.utl.pt:9003/MultiCastController" displayStringBundleKey="ReCLabeLab$rec.lab.title.elab" toolTipBundleKey="ReCLabeLab$rec.lab.tip.elab" iconLocationBundleKey="ReCBaseUI$rec.bui.icon.lab" desktopLocationBundleKey="ReCBaseUI$rec.bui.image.desktop" order="1">
	 <!--<LocalizationBundle name="bundleName" 
			     location="bundleLocation"/>
	 <LocalizationBundle name="bundleName" 
			     location="bundleLocation"/>-->
	<WebResource locationBundleKey="ReCLabeLab$rec.lab.url.elab" iconLocationBundleKey="ReCLabeLab$rec.lab.icon.webpage" displayStringBundleKey="ReCLabeLab$rec.lab.url.title.elab" toolTipLocationBundleKey="ReCLabeLab$rec.lab.url.tip.elab" internalBrowser="false" order="1"/>    	 
	<!--<WebResource locationBundleKey="ReC_Base_Test$lab_elab_web_url_eescola"
		      iconLocationBundleKey="ReCBaseUI$rec.bui.icon.web"
		      displayStringBundleKey="ReC_Base_Test$lab_elab_web_url_eescola"
		      toolTipLocationBundleKey="ReC_Base_Test$lab_elab_web_tip_eescola"
		      internalBrowser="false"
		      order="2"/>-->
	 <Apparatus location="ELAB_G_STAMP_V02" customizerClassLocationBundleKey="ReCExpG$rec.exp.customizer.g" toolTipBundleKey="ReCExpG$rec.exp.tip.g" iconLocationBundleKey="ReCExpG$rec.exp.icon.g" displayStringBundleKey="ReCExpG$rec.exp.title.g" desktopLocationBundleKey="ReCExpG$rec.exp.background.g" order="1">
<!--	    <LocalizationBundle name="ReCExpSemiconductors" 
				location="recresource:///pt/utl/ist/elab/virtual/client/semiconductor/resources/ReCExpSemiconductors"/>-->
	<!--    <WebResource locationBundleKey="ReC_Base_Test$rec.exp.url.radiare.2" 
			 iconLocationBundleKey="ReCBaseUI$rec.bui.icon.web" 
			 displayStringBundleKey="ReC_Base_Test$rec.exp.url.title.radiare.2" 
			 toolTipLocationBundleKey="ReC_Base_Test$rec.exp.url.title.radiare.2" 
			 internalBrowser="false"
			 order="2"/>-->
            <WebResource locationBundleKey="ReCExpG$rec.exp.url.g.1" iconLocationBundleKey="ReCLabeLab$rec.lab.icon.webpage" displayStringBundleKey="ReCExpG$rec.exp.url.g.title.1" toolTipLocationBundleKey="ReCExpG$rec.exp.url.g.title.1" internalBrowser="false" order="1"/>
	    <WebResource locationBundleKey="ReCExpG$rec.exp.url.g.2" iconLocationBundleKey="ReCLabeLab$rec.lab.icon.webpage" displayStringBundleKey="ReCExpG$rec.exp.url.g.title.2" toolTipLocationBundleKey="ReCExpG$rec.exp.url.g.title.2" internalBrowser="false" order="2"/>
	    <WebResource locationBundleKey="ReCExpG$rec.exp.url.g.video" iconLocationBundleKey="ReCBaseUI$rec.bui.icon.movie" displayStringBundleKey="ReCExpG$rec.exp.url.g.title.video" toolTipLocationBundleKey="ReCExpG$rec.exp.url.g.title.video" internalBrowser="false" order="3"/>

	    <DefaultAcquisitionConfig classLocationBundleKey="ReCExpG$rec.exp.dftcfg.g.loc.1" toolTipBundleKey="ReCExpG$rec.exp.dftcfg.g.tip.1" iconLocationBundleKey="ReCBaseUI$rec.bui.icon.customize" displayStringBundleKey="ReCExpG$rec.exp.dftcfg.g.title.1" order="1"/>
