=== linkareti/rec-project/last-successfull/eLab/rec/src/java/common/com/linkare/rec/impl/utils/HardwareInfoSchema.dtd
<?xml version='1.0' encoding='UTF-8'?>

<!--
    Typical usage:

    <?xml version="1.0"?>

    <!DOCTYPE HardwareInfo SYSTEM "HardwareInfoSchema.dtd">

    <HardwareInfo>
    ...
    </HardwareInfo>
-->

<!ELEMENT AvailableOutputIDataSource EMPTY>
<!ATTLIST AvailableOutputIDataSource
    href CDATA #IMPLIED
  >

<!ELEMENT ChannelInfo (AvailableOutputIDataSource|Frequency|customizer|sampling-scale|scale|frequency-scale|parameter)*>
<!ATTLIST ChannelInfo
    direction CDATA #IMPLIED
    independent CDATA #IMPLIED
    name CDATA #IMPLIED
  >

<!ELEMENT Frequency (#PCDATA)>
<!ATTLIST Frequency
    type CDATA #IMPLIED
    multiplier CDATA #IMPLIED
  >

<!ELEMENT HardwareInfo (Frequency|ChannelInfo|customizer|sampling-scale|description|frequency-scale|parameter)*>
<!ATTLIST HardwareInfo
    manufacturer CDATA #IMPLIED
    familiarName CDATA #IMPLIED
    name CDATA #IMPLIED
    driverVersion CDATA #IMPLIED
    id CDATA #IMPLIED
    version CDATA #IMPLIED
  >

<!ELEMENT PhysicsVal (#PCDATA)>
<!ATTLIST PhysicsVal
    href CDATA #IMPLIED
    type CDATA #IMPLIED
    file CDATA #IMPLIED
    mimetype CDATA #IMPLIED
  >

<!ELEMENT description (#PCDATA)>

<!ELEMENT errordefault (#PCDATA|PhysicsVal)*>

<!ELEMENT frequency-scale (step-frequency|min-frequency|max-frequency)*>
<!ATTLIST frequency-scale
    label CDATA #IMPLIED
  >

<!ELEMENT max (PhysicsVal)*>

<!ELEMENT max-frequency (Frequency)*>

<!ELEMENT max-samples (#PCDATA)>

<!ELEMENT min (PhysicsVal)*>

<!ELEMENT min-frequency (Frequency)*>

<!ELEMENT min-samples (#PCDATA)>

<!ELEMENT parameter (selection-list)*>
<!ATTLIST parameter
    value CDATA #IMPLIED
    type CDATA #IMPLIED
    name CDATA #IMPLIED
  >

<!ELEMENT sampling-scale (min-samples|max-samples|step-samples)*>

<!ELEMENT scale (min|errordefault|step|max)*>
<!ATTLIST scale
    selected CDATA #IMPLIED
    label CDATA #IMPLIED
    physicsunitname CDATA #IMPLIED
    multiplier CDATA #IMPLIED
    physicsunitsymbol CDATA #IMPLIED
  >

<!ELEMENT selection-list (value)*>

<!ELEMENT step (PhysicsVal)*>

<!ELEMENT step-frequency (Frequency)*>

<!ELEMENT step-samples (#PCDATA)>

<!ELEMENT value (#PCDATA)>
<!ATTLIST value
    order CDATA #IMPLIED
  >

=== linkareti/rec-project/experiments/wpprague/src/java/server/pt/utl/ist/elab/driver/wpprague/HardwareInfo.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE HardwareInfo PUBLIC "-//Linkare/ReC/HardwareInfo//-" "http://rec.linkare.com/HardwareInfoSchema.dtd">
<HardwareInfo id="WP_PRG" familiarName="Pêndulo Mundial Prague" name="Basic STAMP"
	version="BS2" manufacturer="Parallax" driverVersion="v2">
	
	<description>	</description>
	
	<parameter name="wpprague$parameter.displacement" type="ContinuousValue" value="5">
		<selection-list>
			<value order="1">5</value>
			<value order="2">20</value>
			<value order="3">1</value>
		</selection-list>
	</parameter>

	<parameter name="wpprague$parameter.nrpoints" type="ContinuousValue" value="10">
		<selection-list>
			<value order="1">10</value>
			<value order="2">1000</value>
			<value order="3">1</value>
		</selection-list>
	</parameter>

	<frequency-scale label="Sampling Interval">
		<min-frequency><Frequency type="SamplingIntervalType" multiplier="none">1</Frequency></min-frequency>
		<max-frequency><Frequency type="SamplingIntervalType" multiplier="none">10</Frequency></max-frequency>
		<step-frequency><Frequency type="SamplingIntervalType" multiplier="none">1</Frequency></step-frequency>
	</frequency-scale>
	<Frequency type="SamplingIntervalType" multiplier="none">1</Frequency>
	
	<sampling-scale>
		<min-samples>10</min-samples>
		<max-samples>1000</max-samples>
		<step-samples>1</step-samples>
	</sampling-scale>

	<ChannelInfo name="wpprague$channel.0.name" independent="false" direction="CHANNEL_INPUT">
		<scale label="wpprague$channel.0.label" physicsunitname="wpprague$channel.0.physicsunitname" physicsunitsymbol="N" multiplier="none" selected="true">
			<min><PhysicsVal type="float">1</PhysicsVal></min>
			<max><PhysicsVal type="float">1000</PhysicsVal></max>
			<step><PhysicsVal type="float">1</PhysicsVal></step>
			<errordefault><PhysicsVal type="float">0.</PhysicsVal></errordefault>
		</scale>
	</ChannelInfo>

	<ChannelInfo name="wpprague$channel.1.name" independent="false" direction="CHANNEL_INPUT">
		<scale label="wpprague$channel.1.label" physicsunitname="wpprague$channel.1.physicsunitname" physicsunitsymbol="seg" multiplier="none" selected="true">
			<min><PhysicsVal type="float">0.1</PhysicsVal></min>
			<max><PhysicsVal type="float">10</PhysicsVal></max>
			<step><PhysicsVal type="float">0.1</PhysicsVal></step>
			<errordefault><PhysicsVal type="float">0.0005</PhysicsVal></errordefault>
		</scale>
	</ChannelInfo>

	<ChannelInfo name="wpprague$channel.2.name" independent="false" direction="CHANNEL_INPUT">
		<scale label="wpprague$channel.2.label" physicsunitname="wpprague$channel.2.physicsunitname" physicsunitsymbol="m/s²" multiplier="none" selected="true">
			<min><PhysicsVal type="float">0.</PhysicsVal></min>
			<max><PhysicsVal type="float">20</PhysicsVal></max>
			<step><PhysicsVal type="float">0.000001</PhysicsVal></step>
			<errordefault><PhysicsVal type="float">0.2</PhysicsVal></errordefault>
		</scale>
	</ChannelInfo>

	<ChannelInfo name="wpprague$channel.3.name" independent="false" direction="CHANNEL_INPUT">
		<scale label="wpprague$channel.3.label" physicsunitname="wpprague$channel.3.physicsunitname" physicsunitsymbol="cm/s" multiplier="none" selected="true">
			<min><PhysicsVal type="float">0.</PhysicsVal></min>
			<max><PhysicsVal type="float">200</PhysicsVal></max>
			<step><PhysicsVal type="float">0.000001</PhysicsVal></step>
			<errordefault><PhysicsVal type="float">0.0151230</PhysicsVal></errordefault>
		</scale>
	</ChannelInfo>

	<ChannelInfo name="wpprague$channel.4.name" independent="false" direction="CHANNEL_INPUT">
		<scale label="wpprague$channel.4.label" physicsunitname="wpprague$channel.4.physicsunitname" physicsunitsymbol="ºC" multiplier="none" selected="true">
			<min><PhysicsVal type="float">0.</PhysicsVal></min>
			<max><PhysicsVal type="float">40</PhysicsVal></max>
			<step><PhysicsVal type="float">0.1</PhysicsVal></step>
			<errordefault><PhysicsVal type="float">0.</PhysicsVal></errordefault>
		</scale>
	</ChannelInfo>	
</HardwareInfo>

=== linkareti/rec-project/last-successfull/ReC/experiments/vdi/src/java/server/pt/utl/ist/elab/driver/vdi/HardwareInfo.xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- Created by pqueiro on 3 de Abril de 2005, 06:54 -->

<!DOCTYPE HardwareInfo PUBLIC "-//Linkare/ReC/HardwareInfo//-" "http://rec.linkare.com/HardwareInfoSchema.dtd">
<HardwareInfo id="DISCOS_INERCIA_V1.0" familiarName="Discos-Inercia" name="Discos-Inercia" version="01" manufacturer="Elab - UTL" driverVersion="v1">
    <description>
        <![CDATA[ 
        Esta experiencia serve para simular a descida de dois discos de diferente 
        momento de inercia ao longo de um plano inclinado.
        <b>Penso que pode ter coisas maradas aqui como html</b>
        ]]>
    </description>
            
    <parameter name="r1i" type="ContinuousValue" value="0.15">
        <selection-list>
            <value order="1">0</value>
            <value order="2">0.15</value>
	    <value order="3">0.001</value>
        </selection-list>
    </parameter>
    <parameter name="r1e" type="ContinuousValue" value="0.15">
        <selection-list>
            <value order="1">0.15</value>
            <value order="2">0.30</value>
	    <value order="3">0.001</value>
        </selection-list>
    </parameter>
    <parameter name="r2i" type="ContinuousValue" value="0">
        <selection-list>
            <value order="1">0</value>
            <value order="2">0.15</value>
	    <value order="3">0.001</value>
        </selection-list>
    </parameter>
    <parameter name="r2e" type="ContinuousValue" value="0.15">
        <selection-list>
            <value order="1">0.15</value>
            <value order="2">0.30</value>
	    <value order="3">0.001</value>
        </selection-list>
    </parameter>
    <parameter name="m1" type="ContinuousValue" value="0.5">
        <selection-list>
            <value order="1">0.1</value>
            <value order="2">1</value>
	    <value order="3">0.001</value>
        </selection-list>
    </parameter>
    <parameter name="m2" type="ContinuousValue" value="0.5">
        <selection-list>
            <value order="1">0.1</value>
            <value order="2">1</value>
	    <value order="3">0.001</value>
        </selection-list>
    </parameter>
    <parameter name="inc" type="ContinuousValue" value="20">
        <selection-list>
            <value order="1">0</value>
            <value order="2">45</value>
	    <value order="3">0.1</value>
        </selection-list>
    </parameter>
	
    <frequency-scale label="Sampling Interval">
        <min-frequency><Frequency type="SamplingIntervalType" multiplier="milli">20</Frequency></min-frequency>
        <max-frequency><Frequency type="SamplingIntervalType" multiplier="milli">50</Frequency></max-frequency>
        <step-frequency><Frequency type="SamplingIntervalType" multiplier="milli">1</Frequency></step-frequency>
    </frequency-scale>
    <Frequency type="SamplingIntervalType" multiplier="none">30</Frequency>
    
    <sampling-scale>
        <min-samples>10</min-samples>
        <max-samples>150</max-samples>
        <step-samples>1</step-samples>
    </sampling-scale>

    <ChannelInfo name="T. Relativo" independent="false" direction="CHANNEL_INPUT">
        <scale label="Tempo Relativo" physicsunitname="segundos" physicsunitsymbol="s" multiplier="none" selected="true">
            <min><PhysicsVal type="float">-1</PhysicsVal></min>
            <max><PhysicsVal type="float">10000</PhysicsVal></max>
            <step><PhysicsVal type="float">0.01</PhysicsVal></step>
            <errordefault><PhysicsVal type="float">1</PhysicsVal></errordefault>
        </scale>  
    </ChannelInfo>
    <ChannelInfo name="x1" independent="false" direction="CHANNEL_INPUT">
        <scale label="Deslocamento X 1" physicsunitname="metro" physicsunitsymbol="m" multiplier="none" selected="true">
            <min><PhysicsVal type="float">-1</PhysicsVal></min>
            <max><PhysicsVal type="float">1E15</PhysicsVal></max>
            <step><PhysicsVal type="float">0.01</PhysicsVal></step>
            <errordefault><PhysicsVal type="float">0.05</PhysicsVal></errordefault>
        </scale>
    </ChannelInfo>
    <ChannelInfo name="x2" independent="false" direction="CHANNEL_INPUT">
        <scale label="Deslocamento X 2" physicsunitname="metro" physicsunitsymbol="m" multiplier="none" selected="true">
            <min><PhysicsVal type="float">-1</PhysicsVal></min>
            <max><PhysicsVal type="float">1E15</PhysicsVal></max>
            <step><PhysicsVal type="float">0.01</PhysicsVal></step>
            <errordefault><PhysicsVal type="float">0.05</PhysicsVal></errordefault>
        </scale>
    </ChannelInfo>
    <ChannelInfo name="y1" independent="false" direction="CHANNEL_INPUT">
        <scale label="Deslocamento Y 1" physicsunitname="metro" physicsunitsymbol="m" multiplier="none" selected="true">
            <min><PhysicsVal type="float">-1E15</PhysicsVal></min>
            <max><PhysicsVal type="float">1E15</PhysicsVal></max>
            <step><PhysicsVal type="float">0.01</PhysicsVal></step>
            <errordefault><PhysicsVal type="float">0.05</PhysicsVal></errordefault>
        </scale>
    </ChannelInfo>
    <ChannelInfo name="y2" independent="false" direction="CHANNEL_INPUT">
        <scale label="Deslocamento Y 2" physicsunitname="metro" physicsunitsymbol="m" multiplier="none" selected="true">
            <min><PhysicsVal type="float">-1E15</PhysicsVal></min>
            <max><PhysicsVal type="float">1E15</PhysicsVal></max>
            <step><PhysicsVal type="float">0.01</PhysicsVal></step>
            <errordefault><PhysicsVal type="float">0.05</PhysicsVal></errordefault>
        </scale>
    </ChannelInfo>
    <ChannelInfo name="vCM1" independent="false" direction="CHANNEL_INPUT">
        <scale label="Velocidade 1" physicsunitname="metros/segundo" physicsunitsymbol="m/s" multiplier="none" selected="true">
            <min><PhysicsVal type="float">-1</PhysicsVal></min>
            <max><PhysicsVal type="float">1E15</PhysicsVal></max>
            <step><PhysicsVal type="float">0.01</PhysicsVal></step>
            <errordefault><PhysicsVal type="float">0.05</PhysicsVal></errordefault>
        </scale>
    </ChannelInfo>
    <ChannelInfo name="vCM2" independent="false" direction="CHANNEL_INPUT">
        <scale label="Velocidade 2" physicsunitname="metros/segundo" physicsunitsymbol="m/s" multiplier="none" selected="true">
            <min><PhysicsVal type="float">-1</PhysicsVal></min>
            <max><PhysicsVal type="float">1E15</PhysicsVal></max>
            <step><PhysicsVal type="float">0.01</PhysicsVal></step>
            <errordefault><PhysicsVal type="float">0.05</PhysicsVal></errordefault>
        </scale>
    </ChannelInfo>
    <ChannelInfo name="VelAngular1" independent="false" direction="CHANNEL_INPUT">
        <scale label="Velocidade Angular 1" physicsunitname="rad/segundo" physicsunitsymbol="rad/s" multiplier="none" selected="true">
            <min><PhysicsVal type="float">-1</PhysicsVal></min>
            <max><PhysicsVal type="float">1E15</PhysicsVal></max>
            <step><PhysicsVal type="float">0.01</PhysicsVal></step>
            <errordefault><PhysicsVal type="float">0.05</PhysicsVal></errordefault>
        </scale>
    </ChannelInfo>
    <ChannelInfo name="VelAngular2" independent="false" direction="CHANNEL_INPUT">
        <scale label="Velocidade Angular 2" physicsunitname="rad/segundo" physicsunitsymbol="rad/s" multiplier="none" selected="true">
            <min><PhysicsVal type="float">-1</PhysicsVal></min>
            <max><PhysicsVal type="float">1E15</PhysicsVal></max>
            <step><PhysicsVal type="float">0.01</PhysicsVal></step>
            <errordefault><PhysicsVal type="float">0.05</PhysicsVal></errordefault>
        </scale>
    </ChannelInfo>
    <ChannelInfo name="EspacoPercorrido1" independent="false" direction="CHANNEL_INPUT">
        <scale label="Espaco Percorrido 1" physicsunitname="metro" physicsunitsymbol="m" multiplier="none" selected="true">
            <min><PhysicsVal type="float">-1</PhysicsVal></min>
            <max><PhysicsVal type="float">1E15</PhysicsVal></max>
            <step><PhysicsVal type="float">0.01</PhysicsVal></step>
            <errordefault><PhysicsVal type="float">0.05</PhysicsVal></errordefault>
        </scale>
    </ChannelInfo>
    <ChannelInfo name="EspacoPercorrido2" independent="false" direction="CHANNEL_INPUT">
        <scale label="Espaco Percorrido 2" physicsunitname="metro" physicsunitsymbol="m" multiplier="none" selected="true">
            <min><PhysicsVal type="float">-1</PhysicsVal></min>
            <max><PhysicsVal type="float">1E15</PhysicsVal></max>
            <step><PhysicsVal type="float">0.01</PhysicsVal></step>
            <errordefault><PhysicsVal type="float">0.05</PhysicsVal></errordefault>
        </scale>
    </ChannelInfo>
 </HardwareInfo>

=== linkareti/rec-project/last-successfull/ReC/experiments/hidrostat/src/java/server/pt/utl/ist/elab/driver/hidrostat/HardwareInfo.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE HardwareInfo PUBLIC "-//Linkare/ReC/HardwareInfo//-" "http://rec.linkare.com/HardwareInfoSchema.dtd">
<HardwareInfo id="ELAB_HIDROSTAT_DSPIC_V1.0" familiarName="Hidrostat"
	name="Basic STAMP" version="BS2" manufacturer="Parallax" driverVersion="v2">
	<description>
        <![CDATA[ 
        Esta experiência serve para - não esquecer de alterar esta descrição
        <b>Penso que pode ter coisas maradas aqui como html</b>
        ]]>
	</description>

	<parameter name="protocolo" type="ContinuousValue" value="1">
		<selection-list>
			<value order="1">0</value>
			<value order="2">1</value>
			<value order="3">1</value>
		</selection-list>
	</parameter>

	<parameter name="profundidade_inicial" type="ContinuousValue" value="0">
		<selection-list>
			<value order="1">0</value>
			<value order="2">1930</value>
			<value order="3">1</value>
		</selection-list>
	</parameter>

	<parameter name="profundidade_final" type="ContinuousValue" value="1000">
		<selection-list>
			<value order="1">0</value>
			<value order="2">1930</value>
			<value order="3">1</value>
		</selection-list>
	</parameter>

	<parameter name="numero_de_pontos" type="ContinuousValue" value="20">
		<selection-list>
			<value order="1">2</value>
			<value order="2">200</value>
			<value order="3">1</value>
		</selection-list>
	</parameter>

	<frequency-scale label="Sampling Interval">
		<min-frequency>
			<Frequency type="SamplingIntervalType" multiplier="milli">2000</Frequency>
		</min-frequency>
		<max-frequency>
			<Frequency type="SamplingIntervalType" multiplier="milli">5000</Frequency>
		</max-frequency>
		<step-frequency>
			<Frequency type="SamplingIntervalType" multiplier="milli">1</Frequency>
		</step-frequency>
	</frequency-scale>
	<Frequency type="SamplingIntervalType" multiplier="milli">1</Frequency>

	<sampling-scale>
		<min-samples>2</min-samples>
		<max-samples>200</max-samples>
		<step-samples>1</step-samples>
	</sampling-scale>

	<ChannelInfo name="hidrostat$rec.exp.hidrostat.hardwareinfo.channel.0.name"
		independent="false" direction="CHANNEL_INPUT">
		<scale label="hidrostat$rec.exp.hidrostat.hardwareinfo.channel.0.label"
			physicsunitname="hidrostat$rec.exp.hidrostat.hardwareinfo.channel.0.physicsunitname"
			physicsunitsymbol="m" multiplier="milli" selected="true">
			<min><PhysicsVal type="float">0</PhysicsVal></min>
			<max><PhysicsVal type="float">1.9</PhysicsVal></max>
			<step><PhysicsVal type="float">0.001</PhysicsVal></step>
			<errordefault><PhysicsVal type="float">5</PhysicsVal></errordefault>
		</scale>
	</ChannelInfo>

	<ChannelInfo name="hidrostat$rec.exp.hidrostat.hardwareinfo.channel.1.name"
		independent="false" direction="CHANNEL_INPUT">
		<scale label="hidrostat$rec.exp.hidrostat.hardwareinfo.channel.1.label"
			physicsunitname="hidrostat$rec.exp.hidrostat.hardwareinfo.channel.1.physicsunitname"
			physicsunitsymbol="Pa" multiplier="kilo" selected="true">
			<min><PhysicsVal type="float">0</PhysicsVal></min>
			<max><PhysicsVal type="float">30</PhysicsVal></max>
			<step><PhysicsVal type="float">0.001</PhysicsVal></step>
			<errordefault><PhysicsVal type="float">0.01</PhysicsVal></errordefault>
		</scale>
	</ChannelInfo>

	<ChannelInfo name="hidrostat$rec.exp.hidrostat.hardwareinfo.channel.2.name"
		independent="false" direction="CHANNEL_INPUT">
		<scale label="hidrostat$rec.exp.hidrostat.hardwareinfo.channel.2.label"
			physicsunitname="hidrostat$rec.exp.hidrostat.hardwareinfo.channel.2.physicsunitname"
			physicsunitsymbol="Pa" multiplier="kilo" selected="true">
			<min><PhysicsVal type="float">0</PhysicsVal></min>
			<max><PhysicsVal type="float">30</PhysicsVal></max>
			<step><PhysicsVal type="float">0.001</PhysicsVal></step>
			<errordefault><PhysicsVal type="float">0.01</PhysicsVal></errordefault>
		</scale>
	</ChannelInfo>

	<ChannelInfo name="hidrostat$rec.exp.hidrostat.hardwareinfo.channel.3.name"
		independent="false" direction="CHANNEL_INPUT">
		<scale label="hidrostat$rec.exp.hidrostat.hardwareinfo.channel.3.label"
			physicsunitname="hidrostat$rec.exp.hidrostat.hardwareinfo.channel.3.physicsunitname"
			physicsunitsymbol="Pa" multiplier="kilo" selected="true">
			<min><PhysicsVal type="float">0</PhysicsVal></min>
			<max><PhysicsVal type="float">30</PhysicsVal></max>
			<step><PhysicsVal type="float">0.001</PhysicsVal></step>
			<errordefault><PhysicsVal type="float">0.01</PhysicsVal></errordefault>
		</scale>
	</ChannelInfo>

	<ChannelInfo name="hidrostat$rec.exp.hidrostat.hardwareinfo.channel.4.name"
		independent="false" direction="CHANNEL_INPUT">
		<scale label="hidrostat$rec.exp.hidrostat.hardwareinfo.channel.4.label"
			physicsunitname="hidrostat$rec.exp.hidrostat.hardwareinfo.channel.4.physicsunitname"
			physicsunitsymbol="Pa" multiplier="kilo" selected="true">
			<min><PhysicsVal type="float">0</PhysicsVal></min>
			<max><PhysicsVal type="float">30</PhysicsVal></max>
			<step><PhysicsVal type="float">0.001</PhysicsVal></step>
			<errordefault><PhysicsVal type="float">0.01</PhysicsVal></errordefault>
		</scale>
	</ChannelInfo>

</HardwareInfo>

=== linkareti/rec-project/last-successfull/ReC/experiments/telescopio/src/java/server/pt/utl/ist/elab/driver/telescopio/HardwareInfo.xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- Created by jp on 9 de Maio de 2003, 19:07 -->

<!DOCTYPE HardwareInfo PUBLIC "-//Linkare/ReC/HardwareInfo//-" "http://rec.linkare.com/HardwareInfoSchema.dtd">
<HardwareInfo id="ELAB_TELESCOPIO_V01" familiarName="Telescopio" name="Basic STAMP" version="BS2" manufacturer="Parallax" driverVersion="v2">
    <description>
        <![CDATA[ 
        Esta experiência serve para - não esquecer de alterar esta descrição
        <b>Penso que pode ter coisas maradas aqui como html</b>
        ]]>
    </description>
        
    <parameter name="TempoExp" type="ContinuousValue" value="1">
        <selection-list>
            <value order="1">0</value>
            <value order="2">9999999999</value>
	    <value order="2">1</value>
        </selection-list>
    </parameter>
        
    <parameter name="Comando" type="BlackBoxValue" value="none">
    </parameter>    
    
    <frequency-scale label="Sampling Interval">
        <min-frequency><Frequency type="SamplingIntervalType" multiplier="none">1</Frequency></min-frequency>
        <max-frequency><Frequency type="SamplingIntervalType" multiplier="none">10</Frequency></max-frequency>
        <step-frequency><Frequency type="SamplingIntervalType" multiplier="none">1</Frequency></step-frequency>
    </frequency-scale>
    <Frequency type="SamplingIntervalType" multiplier="none">10</Frequency>
    
    <sampling-scale>
        <min-samples>1</min-samples>
        <max-samples>2</max-samples>
        <step-samples>1</step-samples>
    </sampling-scale>

    <ChannelInfo name="Imagem_Telescopio" independent="true" direction="CHANNEL_INPUT">
        <scale label="Imagem_Telescopio" physicsunitname="" physicsunitsymbol="" multiplier="none" selected="true">
            <min><PhysicsVal type="byteArray"  mimetype="file/raw"> </PhysicsVal></min>
            <max><PhysicsVal type="byteArray"  mimetype="file/raw"> </PhysicsVal></max>
            <step><PhysicsVal type="byteArray"  mimetype="file/raw"> </PhysicsVal></step>
            <errordefault><PhysicsVal type="byteArray"  mimetype="file/raw"> </PhysicsVal></errordefault>
        </scale>
    </ChannelInfo>    
    <ChannelInfo name="Imagem_Flat" independent="true" direction="CHANNEL_INPUT">
        <scale label="Imagem_Buscador" physicsunitname="" physicsunitsymbol="" multiplier="none" selected="true">
            <min><PhysicsVal type="byteArray"  mimetype="file/raw"> </PhysicsVal></min>
            <max><PhysicsVal type="byteArray"  mimetype="file/raw"> </PhysicsVal></max>
            <step><PhysicsVal type="byteArray"  mimetype="file/raw"> </PhysicsVal></step>
            <errordefault><PhysicsVal type="byteArray"  mimetype="file/raw"> </PhysicsVal></errordefault>
        </scale>
    </ChannelInfo>        
    <ChannelInfo name="Imagem_DarkFrame" independent="true" direction="CHANNEL_INPUT">
        <scale label="Imagem_DarkFrame" physicsunitname="" physicsunitsymbol="" multiplier="none" selected="true">
            <min><PhysicsVal type="byteArray"  mimetype="file/raw"> </PhysicsVal></min>
            <max><PhysicsVal type="byteArray"  mimetype="file/raw"> </PhysicsVal></max>
            <step><PhysicsVal type="byteArray"  mimetype="file/raw"> </PhysicsVal></step>
            <errordefault><PhysicsVal type="byteArray"  mimetype="file/raw"> </PhysicsVal></errordefault>
        </scale>
    </ChannelInfo>
    <ChannelInfo name="Error_Channel" independent="true" direction="CHANNEL_INPUT">
        <scale label="Error_Channel" physicsunitname="" physicsunitsymbol="" multiplier="none" selected="true">
            <min><PhysicsVal type="byteArray"  mimetype="text/str"> </PhysicsVal></min>
            <max><PhysicsVal type="byteArray"  mimetype="text/str"> </PhysicsVal></max>
            <step><PhysicsVal type="byteArray"  mimetype="text/str"> </PhysicsVal></step>
            <errordefault><PhysicsVal type="byteArray"  mimetype="text/str"> </PhysicsVal></errordefault>
        </scale>
    </ChannelInfo>        
</HardwareInfo>
